In [13]:
import numpy as np
list=[1,2,3,4,5]
list=np.array(list)
type(list)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.eye(5)#used for identity matrix(dignal values)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
new=[1,2,3,4,5,6]
np.reshape(new,(2,3))

array([[1, 2, 3],
       [4, 5, 6]])